# Generated by Django 4.2.13 on 2024-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
