# Generated by Django 4.2.13 on 2024-08-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningpractice',
            name='code',
            field=models.CharField(max_length=12),
        ),
    ]
