# Generated by Django 4.2.13 on 2024-08-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_listeningpractice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningpractice',
            name='number_of_plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='speakingpractice',
            name='number_of_plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='speakingpractice',
            name='question_amount',
            field=models.IntegerField(default=0),
        ),
    ]
