# Generated by Django 4.2.13 on 2024-08-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_listeningpractice_number_of_plays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningpractice',
            name='question_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='answer',
            field=models.CharField(choices=[('1', 'CHOICE 1'), ('2', 'CHOICE 2'), ('3', 'CHOICE 3'), ('4', 'CHOICE 4')], default='1', max_length=1),
        ),
    ]
