# Generated by Django 4.2.13 on 2024-08-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('exercise', '0004_alter_listeningpractice_question_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningpractice',
            name='category',
        ),
        migrations.AddField(
            model_name='listeningpractice',
            name='category',
            field=models.ManyToManyField(related_name='practices', to='category.listeningpracticecategory'),
        ),
    ]
