# Generated by Django 4.2.13 on 2024-08-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('exercise', '0007_alter_speakingtargets_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingpractice',
            name='category',
        ),
        migrations.AddField(
            model_name='speakingpractice',
            name='category',
            field=models.ManyToManyField(related_name='practices', to='category.speakingpracticecategory'),
        ),
    ]
