# Generated by Django 4.2.13 on 2024-08-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_remove_speakingpractice_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='image',
            field=models.FileField(default='12.png', upload_to='images/question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speakingtargets',
            name='image',
            field=models.FileField(default='12.png', upload_to='images/question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listeningpractice',
            name='image_url',
            field=models.FileField(upload_to='images/practice'),
        ),
        migrations.AlterField(
            model_name='speakingpractice',
            name='image_url',
            field=models.FileField(upload_to='images/practice'),
        ),
    ]
